/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.0-10-ga0d6566498-20230322"
#endif /* AVUTIL_FFVERSION_H */
